### ISSUE TITLE
Singleton class `IntegrationTestEnv`

### ISSUE THREAD

**Issue by deyanzz** [hiero-ledger/hiero-sdk-cpp#349]
### Problem

After refactoring all of the Integration tests in https://github.com/hashgraph/hedera-sdk-cpp/issues/284 and https://github.com/hashgraph/hedera-sdk-cpp/issues/340, suggestion for more improvements was discuessed:

> `IntegrationTestEnv` class of some sort that has an `init()` function that can be called in each test's `SetUp()` that checks if its already initialized with the `JSON` data and reads the `JSON` data if it's not initialized. This makes sure that the client and network map are initialized for each test, is independent of test order, and only reads in the `JSON` file once.
(source: [PR #339](https://github.com/hashgraph/hedera-sdk-cpp/pull/339))

### Solution

To add a `Singleton` class named `IntegrationTestEnv`, which will handle loading the configuration data from the JSON file only once.

### Alternatives

To work as it's now - JSON file is being read for each instance of a `BaseIntegrationTest`.

**Comment by gsstoykov** [comment]
I created a `ClientFixture` which would be inherited by the `BaseIntegrationTest` so we can call `getClientInstance()` but when running `ctest`, the instance is initialised every time. If we have a singleton it will be in the memory of a concrete test run. Even if it is static it can't be accessed from a separate process run (aka. a different test). `ctest` ran each test as a separate executable thus leaving this issue as not resolvable due to framework limitations. Discussed with @rwalworth can be closed.
